// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApvfkJH7kV0hXQf9HIOtOnw0JpFxF8jjY',
    appId: '1:896323584949:web:92c9721c5e31e871ec4ffc',
    messagingSenderId: '896323584949',
    projectId: 'app-chat-push-notification',
    authDomain: 'app-chat-push-notification.firebaseapp.com',
    storageBucket: 'app-chat-push-notification.firebasestorage.app',
    measurementId: 'G-YPLM5QGDF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNeAzE-u1tsJ4Fvup2fGZiCx5auxMJcj4',
    appId: '1:896323584949:android:35e5a90feb0225a7ec4ffc',
    messagingSenderId: '896323584949',
    projectId: 'app-chat-push-notification',
    storageBucket: 'app-chat-push-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFaxReYskNlYwoPmjYKVIHvMQ73D-vsIY',
    appId: '1:896323584949:ios:b6cf62bac743ff6dec4ffc',
    messagingSenderId: '896323584949',
    projectId: 'app-chat-push-notification',
    storageBucket: 'app-chat-push-notification.firebasestorage.app',
    iosBundleId: 'com.example.appchatonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFaxReYskNlYwoPmjYKVIHvMQ73D-vsIY',
    appId: '1:896323584949:ios:b6cf62bac743ff6dec4ffc',
    messagingSenderId: '896323584949',
    projectId: 'app-chat-push-notification',
    storageBucket: 'app-chat-push-notification.firebasestorage.app',
    iosBundleId: 'com.example.appchatonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApvfkJH7kV0hXQf9HIOtOnw0JpFxF8jjY',
    appId: '1:896323584949:web:f7bfcedadc1fc2feec4ffc',
    messagingSenderId: '896323584949',
    projectId: 'app-chat-push-notification',
    authDomain: 'app-chat-push-notification.firebaseapp.com',
    storageBucket: 'app-chat-push-notification.firebasestorage.app',
    measurementId: 'G-3E69DTW7SM',
  );
}
